"""
LLM Coach — Proposal Enrichment
=================================
Takes raw heuristic proposals and enriches them with LLM reasoning.

After observers generate proposals the Coach:
  1. Queries episodic memory for related past events
  2. Gets proposal stats for recurrence context
  3. Calls the local LLM (router model) for analysis
  4. Returns enriched proposals with confidence scores, better descriptions,
     priority adjustments, and reasoning

Design:
  - OPTIONAL — if Ollama is down, heuristic proposals pass through unchanged
  - Source field changes from "heuristic" to "coach" when enriched
  - Wired into: shared/proposer.py after run_proposer_full()
"""

import json
import sys
import time
import requests
from typing import List, Dict
from pathlib import Path

_PROJECT_ROOT = Path(__file__).parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from shared.logger import get_logger
from config import CONFIG

logger = get_logger("coach")

OLLAMA_URL     = f"{CONFIG.OLLAMA_HOST}/api/chat"
MODEL_NAME     = CONFIG.MODEL_ROUTER
COACH_TIMEOUT  = 60
MAX_PROPOSALS_PER_BATCH = 6


def _query_memory_for_proposals(proposals: List[Dict]) -> str:
    try:
        from shared.memory import memory
        fragments = []
        seen = set()
        for p in proposals[:MAX_PROPOSALS_PER_BATCH]:
            query = f"[PROPOSAL] {p.get('title', '')}"
            if query in seen:
                continue
            seen.add(query)
            matches = memory.retrieve_relevant(query, limit=2, min_score=2.0)
            for m in matches:
                age_h = (time.time() - m.timestamp) / 3600
                fragments.append(
                    f"- {m.task_query[:80]} | "
                    f"{'Success' if m.success else 'Failed'} | "
                    f"{age_h:.0f}h ago | Utility: {m.utility:.2f}"
                )
        return "RELATED MEMORY:\n" + "\n".join(fragments[:8]) if fragments else "RELATED MEMORY: None found."
    except Exception as e:
        logger.warning(f"Memory query failed: {e}")
        return "RELATED MEMORY: Unavailable."


def _get_stats_context() -> str:
    try:
        from shared.proposal_bus import get_proposal_stats
        stats = get_proposal_stats()
        parts = [f"Total historical proposals: {stats['total']}"]
        if stats.get("recurrences"):
            recur_lines = [
                f"  - \"{r['title']}\" occurred {r['count']}x (last: {r['last_state']})"
                for r in stats["recurrences"][:5]
            ]
            parts.append("Recurring issues:\n" + "\n".join(recur_lines))
        if stats.get("failure_rate", 0) > 0:
            parts.append(f"Overall failure rate: {stats['failure_rate']:.1%}")
        return "\n".join(parts)
    except Exception as e:
        logger.warning(f"Stats query failed: {e}")
        return "Stats: Unavailable."


def _build_coach_prompt(proposals: List[Dict], memory_context: str, stats_context: str):
    system = """You are the Coach for an autonomous agent system called RouxYou.
Your job is to analyze system proposals (generated by heuristic observers) and enrich them.

For each proposal, provide:
1. confidence: 0.0-1.0 (how likely this is a real issue worth acting on)
2. enriched_description: A better description with root cause analysis
3. priority_adjustment: -2 to +2 (adjust priority, 0 = keep as-is)
4. reasoning: One sentence explaining your assessment

Respond with ONLY a JSON array in the same order as the proposals. No markdown, no explanation.

Example:
[
  {"confidence": 0.95, "enriched_description": "Worker crashed — 3rd time in 48h", "priority_adjustment": 1, "reasoning": "Recurring crash pattern"},
  {"confidence": 0.4, "enriched_description": "Unused skills may need better naming", "priority_adjustment": 0, "reasoning": "Low urgency cosmetic issue"}
]"""

    prop_lines = []
    for i, p in enumerate(proposals[:MAX_PROPOSALS_PER_BATCH]):
        prop_lines.append(
            f"Proposal {i+1}:\n"
            f"  Title: {p.get('title','?')}\n"
            f"  Category: {p.get('category','?')}\n"
            f"  Priority: {p.get('priority','?')}\n"
            f"  Description: {p.get('description','?')}\n"
            f"  Evidence: {p.get('evidence','?')}\n"
            f"  Proposed Action: {p.get('proposed_action','?')}"
        )

    user = (
        f"Analyze these {len(proposals[:MAX_PROPOSALS_PER_BATCH])} proposals:\n\n"
        + "\n\n".join(prop_lines)
        + f"\n\n{memory_context}\n\n{stats_context}"
    )
    return system, user


def enrich_proposals(proposals: List[Dict]) -> List[Dict]:
    """
    Main entry point. Enriches raw heuristic proposals via LLM.
    Returns proposals unchanged if Ollama is unavailable.
    """
    if not proposals:
        return proposals

    batch = proposals[:MAX_PROPOSALS_PER_BATCH]
    logger.info(f"COACH: Enriching {len(batch)} proposal(s) via {MODEL_NAME}...")

    memory_context = _query_memory_for_proposals(batch)
    stats_context  = _get_stats_context()
    system_prompt, user_prompt = _build_coach_prompt(batch, memory_context, stats_context)

    try:
        start = time.time()
        resp = requests.post(
            OLLAMA_URL,
            json={
                "model": MODEL_NAME,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user",   "content": user_prompt},
                ],
                "temperature": 0.2,
                "stream": False,
                "format": "json",
            },
            timeout=COACH_TIMEOUT,
        )
        elapsed = time.time() - start
        if resp.status_code != 200:
            logger.warning(f"COACH: Ollama returned {resp.status_code}, skipping enrichment")
            return proposals
        content = resp.json().get("message", {}).get("content", "")
        logger.info(f"COACH: LLM responded in {elapsed:.1f}s")
    except requests.Timeout:
        logger.warning(f"COACH: Ollama timed out after {COACH_TIMEOUT}s, skipping enrichment")
        return proposals
    except requests.ConnectionError:
        logger.warning("COACH: Ollama not reachable, skipping enrichment")
        return proposals
    except Exception as e:
        logger.warning(f"COACH: LLM call failed: {e}")
        return proposals

    try:
        # Strip thinking tags (Qwen3 etc.)
        if "<think>" in content:
            content = content.split("</think>")[-1].strip()
        # Strip markdown fences
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0]
        elif "```" in content:
            content = content.split("```")[1].split("```")[0]

        enrichments = json.loads(content.strip())
        if isinstance(enrichments, dict):
            enrichments = (enrichments.get("proposals") or enrichments.get("results") or
                           enrichments.get("enrichments") or [enrichments])
        if not isinstance(enrichments, list):
            logger.warning(f"COACH: Expected list, got {type(enrichments).__name__}")
            return proposals
    except Exception as e:
        logger.warning(f"COACH: Failed to parse LLM response: {e}")
        return proposals

    enriched_count = 0
    for i, p in enumerate(batch):
        if i >= len(enrichments):
            break
        e = enrichments[i]
        if not isinstance(e, dict):
            continue
        confidence = e.get("confidence")
        if isinstance(confidence, (int, float)) and 0 <= confidence <= 1:
            p["confidence"] = round(float(confidence), 2)
        enriched_desc = e.get("enriched_description", "")
        if enriched_desc and len(enriched_desc) > 10:
            p["description"] = enriched_desc
        adj = e.get("priority_adjustment", 0)
        if isinstance(adj, (int, float)) and -2 <= adj <= 2:
            new_priority = max(1, min(10, p.get("priority", 5) + int(adj)))
            if new_priority != p.get("priority", 5):
                logger.info(f"COACH: Priority {p.get('priority')}→{new_priority} for: {p.get('title','?')[:50]}")
                p["priority"] = new_priority
        p["source"] = "coach"
        reasoning = e.get("reasoning", "")
        if reasoning:
            p["coach_reasoning"] = reasoning
        enriched_count += 1

    logger.info(f"COACH: Enriched {enriched_count}/{len(batch)} proposals")
    return batch + proposals[MAX_PROPOSALS_PER_BATCH:] if len(proposals) > MAX_PROPOSALS_PER_BATCH else proposals
